name: Mirror to other git server
on:
  push:
    branches:
      - main
    tags:
      - "*"
jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: yesolutions/mirror-action@master
        with:
          REMOTE: 'https://gitlab.com/spyoungtech/mirror-action.git'
          GIT_USERNAME: ernestguevarra
          GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}