name: Mirror to Codeberg
on:
  push:
    branches:
      - main
    tags:
      - "*"
jobs:
  mirror-codeberg:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Mirror repository
        id: mirror
        shell: bash
        env:
          CODEBERG_TOKEN: ${{ secrets.CODEBERG_TOKEN }}
        run: |
          set -eu

          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id
          chmod 600 ~/.ssh/id
          export GIT_SSH_COMMAND="ssh -v -i ~/.ssh/id -o StrictHostKeyChecking=no"
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"
          git remote add mirror "$REPO_URL_MIRROR"
          git push --tags --force --prune mirror "refs/remotes/origin/*:refs/heads/*"